#! /bin/sh

bspc config border_width        4
bspc config window_gap          8 

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config normal_border_color "#2b303b"
bspc config active_border_color "#2b303b"
bspc config focused_border_color "#bf616a"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.0

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d {$(echo -e '\uf120'),$(echo -e '\uf269'),$(echo -e '\uf121'),$(echo -e '\uf07b'),$(echo -e '\uf099'),$(echo -e '\uf1bc'),$(echo -e '\uf11b')}

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
#bspc rule -a mplayer2 floating=on
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# Begin sxhkd to detect keystrokes and mouse input
sxhkd &

# Load up the background image
hsetroot -fill ~/Pictures/DesktopBackgrounds/WinterTree.jpg &

# Start lemonbar-xft
~/.config/bspwm/panel/panel &

# Begin redshift
redshift -c ~/.config/redshift/redshift.conf &

# Begin compton for compositing and specify background and config
compton -b --config ~/.config/compton/compton.conf
