#! /bin/sh

bspc config border_width        3
bspc config window_gap          8 

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
#bspc rule -a mplayer2 floating=on
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# Begin sxhkd to detect keystrokes and mouse input
sxhkd &

# Load up the background image
hsetroot -fill ~/Pictures/DesktopBackgrounds/WinterTree.jpg &

# Start lemonbar-xft
~/.config/bspwm/panel/panel &

# Begin redshift
redshift &

# Begin compton for compositing and specify background and config
compton -b --config ~/.config/compton/compton.conf
