#! /bin/sh

. ~/.config/themes/currentTheme/bspwmColors

bspc config border_width        3
bspc config window_gap          10 

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config normal_border_color "$NORMAL_BORDER_COLOR"
bspc config presel_border_color "$PRESEL_BORDER_COLOR"
bspc config normal_sticky_border_color "$NORMAL_STICKY_BORDER_COLOR"
bspc config focused_sticky_border_color "$FOCUSED_STICKY_BORDER_COLOR"
bspc config urgent_border_color "$URGENT_BORDER_COLOR"
bspc config focused_border_color "$FOCUSED_BORDER_COLOR"
bspc config normal_frame_opacity 1.0
bspc config focused_frame_opacity 1.0

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d $(echo -e '\uf109') $(echo -e '\uf121') $(echo -e '\uf120') $(echo -e '\uf07c') $(echo -e '\uf0ac') $(echo -e '\uf0c3') $(echo -e '\uf141') $(echo -e '\uf001')

#bspc rule -a Gimp desktop=^8 follow=on floating=on
#bspc rule -a Chromium desktop=^2

# Begin sxhkd to detect keystrokes and mouse input
sxhkd -c ~/.config/sxhkd/sxhkdrc &

# Load up the background image
feh --bg-scale ~/.config/themes/currentTheme/desktopBackground &

# Start lemonbar-xft
~/.config/panel/panel &

# Begin redshift
#redshift -c ~/.config/redshift/redshift.conf &
