#! /bin/sh

bspc config border_width        3
bspc config window_gap          10 

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config normal_border_color "#282828"
bspc config presel_border_color "#83a598"
bspc config normal_sticky_border_color "#689d6a"
bspc config focused_sticky_border_color "#8ec07c"
bspc config urgent_border_color "#b16286"
bspc config focused_border_color "#5f7ab1"
#bspc config normal_frame_opacity 1.0
#bspc config focused_frame_opacity 1.0

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d $(echo -e '\uf109') $(echo -e '\uf121') $(echo -e '\uf120') $(echo -e '\uf07c') $(echo -e '\uf0ac') $(echo -e '\uf0c3') $(echo -e '\uf141') $(echo -e '\uf001')

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2

# Begin sxhkd to detect keystrokes and mouse input
sxhkd &

# Load up the background image
feh --randomize --bg-scale ~/Pictures/DesktopBackgrounds/* &

# Start lemonbar-xft
~/.config/panel/panel &

# Begin redshift
redshift -c ~/.config/redshift/redshift.conf &

# Begin compton for compositing and specify background and config
compton -b --config ~/.config/compton/compton.conf
